// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85k7vwQLpYXCKWY4ML5hvW1e8t_N-BWk',
    appId: '1:508785285053:web:5a3a28255e6e5c7361e4d4',
    messagingSenderId: '508785285053',
    projectId: 'toatrider',
    authDomain: 'toatrider.firebaseapp.com',
    databaseURL: 'https://toatrider-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toatrider.appspot.com',
    measurementId: 'G-335DNV6RHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPMMTXkHGyNd1HA2jw1mYMyYxP8hcLOA',
    appId: '1:508785285053:android:3bd59ae349a3fd1a61e4d4',
    messagingSenderId: '508785285053',
    projectId: 'toatrider',
    databaseURL: 'https://toatrider-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toatrider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbUiAjzQ_O8c8i5Ub-RpnfqWno6evidqQ',
    appId: '1:508785285053:ios:c3b7c0fd3a7bf43e61e4d4',
    messagingSenderId: '508785285053',
    projectId: 'toatrider',
    databaseURL: 'https://toatrider-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toatrider.appspot.com',
    iosBundleId: 'rw1968.com.users001',
  );
}
